### ISSUE TITLE
Itty bitty bugs I see:

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/california-civic-data-coalition.github.io#11]
- [x] Body copy is hard to read and makes me squint
- [ ] Hovering over the header labels from a post makes the top bar bump down almost like an animation
- [x] Footer project list should make the homepage project list

**Comment by sahilchinoy** [comment]
I bumped the font size and fixed the footer. Can't reproduce the header bug, though — let me know if it comes back.

**Comment by palewire** [comment]
Excellent.
